name: dev
on: 
  workflow_dispatch:
  push:
    branches: 
      - '*main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo feature-branch
      - name: checkout code
        id: checkout-code
        uses: actions/checkout@v3
