name: main
run-name: main
on: 
  workflow_dispatch:
  push:
    branches: 
      - '**main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        id: checkout-code-1
        uses: actions/checkout@v3
        with:
         token: ${{ secrets.GH_T }}
         repo: ghaction
         ref: main
         path: gh1
         
      - name: checkout code
        id: checkout-code-2
        uses: actions/checkout@v3
        with:
         token: ${{ secrets.GH_T }}
         path: gh2

      - name: push to other repo
        run: |
          echo "gh1" && cd gh1/.github/workflows/ && ls -a
          #echo "gh2" && ls gh2 -a
          cp -f gh1/.github/workflows/test.yml gh2/.github/workflows/test.yml
          cd gh2
          git config --global user.name "vivek"
          git config --global user.email "don@example.com"
          git remote add dest https://github.com/vivekacoustic/ghaction.git
          git checkout -b "cloned_branch"
          git push dest -f


          
