name: dev
run-name: main
on: 
  workflow_dispatch:
  # push:
  #   branches: 
  #     - '**main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        id: checkout-code
        uses: actions/checkout@v3
